question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "A shrimp's heart is located in its head.", "answer": "True"},
    {"text": "The shortest war in history lasted 38 to 45 minutes.", "answer": "True"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "Humans share 60% of their DNA with bananas.", "answer": "True"},
    {"text": "A jiffy is an actual unit of time, equivalent to 1/100th of a second.", "answer": "True"},
    {"text": "It rains diamonds on Jupiter and Saturn.", "answer": "True"},
    {"text": "Bananas are berries, but strawberries are not.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "A crocodile can't stick its tongue out.", "answer": "True"},
    {"text": "Sharks are the only fish that can blink with both eyes.", "answer": "False"},
    {"text": "Cows have best friends and get stressed when they are separated.", "answer": "True"},
    {"text": "It is impossible for most people to lick their own elbow.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "The first computer virus was created in 1986.", "answer": "True"},
    {"text": "An octopus can change color to blend in with its surroundings.", "answer": "True"},
    {"text": "The longest recorded flight of a chicken is 13 seconds.", "answer": "True"},
    {"text": "Pineapples grow on trees.", "answer": "False"},
    {"text": "Koalas sleep for up to 22 hours a day.", "answer": "True"}
]

